### ISSUE TITLE
Delete images in the project

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#130]
**Tasks**
The mockup was designed to have a quick win and avoid redesign of the image component (which will be necessary when will have tags, selection etc.)
- [ ] In Images tab allow to delete by clicking on the bin. Display the confirmation modal.
- [x] Create Delete Image resolver
  - [x] Delete labels on the deleted image
  - [x] Delete image from storage

Mockup (check links for ground truth)

- https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=2698%3A12087
- https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=2703%3A12359

**Comment by nicOwlas** [comment]
Issue updated with mockup links (always check the links for the ground truth, screenshots can be outdated). Validated at today's DSM.

![image](https://user-images.githubusercontent.com/16015322/132843146-6354e9c3-ff7c-4b91-b237-08924aecdeb8.png)
![image](https://user-images.githubusercontent.com/16015322/132843114-51a18130-3552-4fdb-a0ef-f646bf3c0bcf.png)
