### ISSUE TITLE
On first connection, bring the user directly to the labelling interface instead of the project page.

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#295]
# Tasks

On first connection, we want the user to directly taste and feel the product and be guided. A default project is created with some demo images automatically loaded in it.

- [x] On first connection: create a first project `Demo project`
- [ ] Import images (stored on GitHub labelflow) to the project.
- [x] After the service worker loading is finished the first demo image is displayed to the user once done
- [ ] Add demo images to github repo

Nicolas will create the demo images.
