### ISSUE TITLE
Write github repo readme.md and make repo public

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#307]
# Tasks

The goal is to guide the developer who want to run labelflow.ai locally

- [ ] Explain how to run the labelflow app (local projects only)
- [ ] Set license to BSL (check https://github.com/getsentry/sentry/blob/master/LICENSE)
- [ ] Commit LICENSE file attached at root of repo.  [LICENSE v2.txt](https://github.com/Labelflow/labelflow/files/7037620/LICENSE.v2.txt)
- [ ] Update `Change date` in LICENSE file with the release date of each version 
- [ ] Set the repo to be public

⚠️ Note that the change date should be automatically updated to the release date:
![image](https://user-images.githubusercontent.com/16015322/129949101-b1df6fb8-0f89-4fed-978e-929bc0864f16.png)
