### ISSUE TITLE
Redirects mutation and queries to the app built-in specific end point

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#312]
**Tasks**

- [x] An app is built to talk with a unique end point: local or online
- [x] By default the app talks to the local end-point: localhost:5000/graphql
- [x] Create an env variable to set the end point
- [x] Redirects mutation and queries to the env variable set end point 
https://github.com/Labelflow/labelflow/blob/research/repository/typescript/web-app/src/connectors/apollo-client-service-worker/index.ts#L4
