### ISSUE TITLE
Create file upload resolver for online storage

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#314]
**Tasks**

- [ ] Create back end file upload resolver to upload files to the S3 bucket
- [ ] use `getSignedUrl` from AWS S3
- [ ] Create a subfolder or a bucket per workspace? To be investigated. Is a solution more efficient/economic than another one?

Blocked by #313
