### ISSUE TITLE
Use NextAuth to sign-in / sign-up

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#315]
**Tasks**

**⚠️ Pull request of this issue is to be merged on `Feature/remote server` feature branch, not on main!**

- [x] Implement NextAuth to sign-in / sign-up using default NextAuth pages (accessible via url). https://next-auth.js.org/configuration/pages
- https://labelflow.ai/api/auth/signin
- https://labelflow.ai/api/auth/signout
- [x] Use the Prisma database adaptor of NextAuth (will create user, session table etc. among other things)
- [x] Setup sign-in with Github, Google and Email magic link
- [ ] On sign-out, redirect to url `https://labelflow.ai/local/datasets`

**Comment by etiennedupont** [comment]
@nicOwlas we decided with @crubier that 

>  On sign-out, redirect to url https://labelflow.ai/local/datasets

would be done separately, because it violated the first requirements stating we'd use the default pages.

**Comment by nicOwlas** [comment]
Ok! What happens on sign-out then? There is a default NextAuth page to which we are redirected?
 I'll move the redirections to the next issue.

**Comment by etiennedupont** [comment]
Nothing really, I mean you remain on the sign-out page. But since we don't even have a button to get on that page from the navbar, it doesn't harm the user experience.

**Comment by nicOwlas** [comment]
Ok. The users won't see this before all the [online project milestone](https://github.com/Labelflow/labelflow/milestone/18) issues are merged on the feature branch.
