### ISSUE TITLE
Create user menu in the top right

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#316]
**Tasks**

- [ ] Use chakra menu: https://chakra-ui.com/docs/overlay/menu and put as in icon user' initials or picture if available
- [ ]  Replace sign-in / sign-up icons with user menu when user is signed-in
- [ ] Allow to sign-out/sign-in
- [ ] Allow to switch workspace (change url)
- [ ] Display the local workspace + list of online workspaces

Blocked by #317
