### ISSUE TITLE
CRUD users

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#320]
**Tasks**
- [ ] Write type definitions
- [ ] Graphql fields:  `socialIdGoogle`, `socialIdGithub` (to be investigated is it needed or a lookup based on email is enough?), `name`, `email`, `id`, `workspace`, `role` (`owner`, `admin`), `createdAt`, `updatedAt`
- [ ]  Create resolvers to read / create / list / update  / delete 
- [ ] Add to Workspace table definition the column user id
- [ ] Create a join table to link the user table and the workspace table (many to many relationship as per the wireframe of [teams](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=1850%3A15154) and [workspaces](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=1865%3A12984) done in the Design Sprint)
