### ISSUE TITLE
Add sign-in in navbar + design sign-in modals

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#350]
**Tasks**
Continuation of issue #315. **⚠️Pull request of this issue is to be merged on a Feature branch not on main!**

- [x] Add `"Sign-in"` button in navigation bar (see mockup for the exact call to action text)
- [x] When signed-in remove `"Sign-in"` button from navbar
- [x] User menu: use user initials (e.g. ND) or picture if available as icon (https://chakra-ui.com/docs/overlay/menu)
- [x] Add sign-out to user menu
- [x] On sign-out, redirect to url https://labelflow.ai/local/datasets
- [x] Create modals to allow the user to sign-in with Email, Google & Github

### Mockup

- [Navigation bar](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=839%3A0)
- [Sign in modal](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=2597%3A12139)

blocked by #315

**Comment by nicOwlas** [comment]
Sign-in modal mock-up updated

**Comment by crubier** [comment]
Todo:

- [ ] On sent email, show "Check your inbox" in the signin modal

**Comment by crubier** [comment]
Couple screenshots

<img width="521" alt="Screenshot 2021-09-06 at 19 54 11" src="https://user-images.githubusercontent.com/2954572/132254051-aab0418f-1610-45e6-bf22-b242a9a5e925.png">

**Comment by crubier** [comment]
<img width="461" alt="Screenshot 2021-09-06 at 19 54 06" src="https://user-images.githubusercontent.com/2954572/132254036-2534669d-3b12-4e2b-b653-46693564c869.png">

**Comment by crubier** [comment]
<img width="418" alt="Screenshot 2021-09-06 at 19 53 09" src="https://user-images.githubusercontent.com/2954572/132253991-25def8e6-fac2-4e4d-8bda-276eb40ae889.png">

**Comment by crubier** [comment]
<img width="364" alt="Screenshot 2021-09-06 at 19 53 34" src="https://user-images.githubusercontent.com/2954572/132253996-7920b6b9-b62d-4db6-b2aa-08ea37c15463.png">

**Comment by nacho-carnicero** [comment]
Process with the changes we discussed this morning:

![signin](https://user-images.githubusercontent.com/17384901/132368835-402369ee-e749-4ad1-b790-026e65635c98.gif)
