### ISSUE TITLE
Update urls with local workspace

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#352]
# Tasks

We will add a `local` (in reference to the local workspace) into the url so that booked urls do not change when we roll-out workspaces

- `https://labelflow.ai/`: 
  - [x] Redirect to `https://labelflow.ai/website` on first ever connection OR
  - [x] Redirect to `https://labelflow.ai/local` for successive connections if users has clicked on `Test the app` on the website.
  - (In the future) Redirect to `https://labelflow.ai/my-workspace` , where `my-workspace` is the last workspace the user has worked on. 
- [x] `https://labelflow.ai/website`: website always
- [x] `https://labelflow.ai/local`: shows the datasets of the workspace `local` 
- [x] `https://labelflow.ai/workspaces/local`: Redirect to `https://labelflow.ai/local` (this exist to allow workspaces to contain datasets that are called with special names such as `billing` or `settings`, see #296)
- [x] `https://labelflow.ai/local/datasets/my-dataset/images/` : image gallery page
- [x] `https://labelflow.ai/local/datasets/my-dataset/images/b0a25998-36c4-46db-9b6b-b9620a169608`: use image id to reach the image labelling page
- [x] `https://labelflow.ai/local/datasets/my-dataset/classes/` : list dataset classes
- [ ] `https://labelflow.ai/local/**`: `local` is the slug of the local workspace, all urls with `local` are the same as the ones with `my-workspace`, `local` is just a special name.
