### ISSUE TITLE
Update images in tutorial dataset

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#364]
**Tasks**

- [x] Replace images in the demo dataset with images in zip file attached
- [x] Name the dataset `Tutorial dataset`
- [x] Create the "Horse" class inside the dataset
- [x] Add the labels contained in the annotation json to the `Tutorial image 3`

([Figma project](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/?node-id=2238%3A12033))

[TutorialImages.zip](https://github.com/Labelflow/labelflow/files/7031154/TutorialImages.zip)
[annotations.json.zip](https://github.com/Labelflow/labelflow/files/7031151/annotations.json.zip)
