### ISSUE TITLE
Make class creation more discoverable

### ISSUE THREAD

**Issue by nicOwlas** [Labelflow/labelflow#378]
**Tasks**
In order to make the class creation more discoverable, update the text `Search...` by `Search or Add...`. Icon is also updated
- [x] Update the class menu on the labelling interface
- [x] Update the context class menu (menu which appears after a right click on a label)
- [x] [Mockup](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/Labelflow-mockups?node-id=697%3A453)
![image](https://user-images.githubusercontent.com/16015322/130944804-2f6a913a-c4a2-46ed-8605-ca7e97fd26d4.png)
