### ISSUE TITLE
Add Privacy policy / Cookie Policy & Terms and conditions

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#441]
**Tasks**
Add to Website footer, links to those pages. The content can be dynamically changed by iubenda (to be up to date with latest laws, services used etc.). Therefore there are several options to grab the content:
![image](https://user-images.githubusercontent.com/16015322/133099433-254a2729-615a-4cfa-9c54-f45cf182d585.png)
- [x] [Policies are available here](https://www.iubenda.com/en/flow/2346794) (ask Nicolas for his credentials to access labelflow account on iubenda)
- [x] Add to website footer, three pages with their content:
  - [x] Privacy policy
  - [x] Cookie policy
  - [x] In the cookie banner, redirect the `Learn More` to the cookie policy page
  - [x] Terms & Conditions

### Help pages
- [Video on how to integrate the policies to our site](https://www.iubenda.com/en/help/317-add-privacy-policy-to-your-site-video).
- [Ways to Use iubenda’s Privacy Policy on Your Site and App](https://www.iubenda.com/en/help/231-ways-to-use-iubenda-privacy-policy-on-your-site-and-app)
