### ISSUE TITLE
Add classification tool

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#446]
### Tasks
(will eventually be split in several issues at grooming)

- [x] Add the tag tool to the list of tools in the labelling interface
- [x] When a class is selected with the tag tool selected, a tag of the given class is added (tags are using Chakra UI component: Tag/Square/Icon Left/Small)
- [x] There cannot be two tags of the same class
- [x] A tag can be removed by clicking on its `x`
- [x] The class name inside the tag is either white or chakra gray-800 whichever maximizes the contrast
- [x] The class selection menu width needs to be set to a maximum to avoid pushing the tags all the way to the right (today a very long class name occupies the complete screen width)
- [x] Right click on the image displays the context class selection menu and also allows to add tag
- [x] Add `tag` as a label type
- [x] ~~Update COCO export resolver to export tags~~ Moved to https://github.com/labelflow/labelflow/issues/485
- [x] ~~Update YOLO export resolver to export tags~~ Moved to https://github.com/labelflow/labelflow/issues/485

### Questions / Remarks for discussion
- In terms of UX/UI it would be better when the class selection menu is expanded to be able to select/unselect multiple class.
- When we will have tools with options (accuracy of smart tools for instance), it will move tags further to the right
- Set a maximum width for tags (in the case a class name is very long)
- There can be several rows of tags if there are many many?
- Tags interfere with the drawing area, to test in practice if its problematic

### Design
[Mockup (source of truth)](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=2728%3A15203)
![image](https://user-images.githubusercontent.com/16015322/133161691-d985d433-63bf-4709-ba00-690a5b48730f.png)

**Comment by nicOwlas** [comment]
Some examples of classification files COCO export:
Sample 1: (1 tag per image) [Power grid.v1i.folder.zip](https://github.com/labelflow/labelflow/files/7185119/Power.grid.v1i.folder.zip)
Sample 2: (4 images exported: image1 & image2 with tags only, image3 with tag + polygon, image4 with nothing): 
[2021-09-17-export-coco.zip](https://github.com/labelflow/labelflow/files/7185135/2021-09-17-export-coco.zip)

**Comment by crubier** [comment]
- The first ZIP only contains images nothing else
- The second zip stores classifications as a list of tag_ids on each images. And has a list of tag_gategories
