### ISSUE TITLE
Use MJML in sign up and sign in email

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#462]
### Objective
The goal is to be able to send emails to users for various needs LabelFlow could have. eg:

### Tasks

- [x] Implement function [MJML to HTML](https://github.com/mjmlio/mjml) (12.5k ⭐️)
- [x] Implement the send verification email function from NextAuth: https://next-auth.js.org/providers/email#configuration to use MJML

### Sign up
- [x] [Design and code (in MJML) Sign-up email](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3062%3A9920)
- Icon: ![maracas, music, entertainment, musical, instrument 1](https://user-images.githubusercontent.com/16015322/136012289-c06dcc0f-7865-4153-b427-7630f6d749bc.png)

# Sign in
- [x] [Design and code (in MJML) Sign-in email](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3062%3A10031)
- icon: <img width="96" alt="password, login, account, user, profile, website, webpage, browser, development@2x" src="https://user-images.githubusercontent.com/16015322/136012054-1cac5fa1-e60c-494b-a934-ec3b43b5848d.png">

**Comment by etiennedupont** [comment]
@nicOwlas to your mind, what should we write instead of that text for a hybrid sign-up / sign-in email?

<img width="528" alt="Screenshot 2021-10-04 at 17 16 33" src="https://user-images.githubusercontent.com/23740011/135877704-a7ef0810-df25-47d3-97b7-65775357362d.png">

**Comment by nicOwlas** [comment]
👀 Coming back to you shortly with something.

**Comment by nicOwlas** [comment]
I'll go for two distinct emails for the welcome (sign up) and the following ones (sign-in). I'll send you the sign-up tomorrow. Here is the sign-in one.


## Sign-in ([mockup link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3062%3A9920))
![image](https://user-images.githubusercontent.com/16015322/135885698-05bd891f-b5e7-41bb-aae5-4794887d03f6.png)

png icon:
<img width="96" alt="password, login, account, user, profile, website, webpage, browser, development@2x" src="https://user-images.githubusercontent.com/16015322/135885898-29b3b8ea-b7e6-46ee-ab1e-d54b4799975b.png">


Inspiration:

### Slack magic link email
![image](https://user-images.githubusercontent.com/16015322/135880206-8566b502-d355-4d99-b242-b4d98dd6106d.png)

### Front Egg
![image](https://user-images.githubusercontent.com/16015322/135881260-c92c7312-6ec7-4079-9d72-e6c7ebd351fa.png)

### Excalidraw
![image](https://user-images.githubusercontent.com/16015322/135881342-a302081f-d018-4216-9d54-1e7dc5540fc5.png)
