### ISSUE TITLE
Get user's email address when using GitHub social sign-in

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#471]
**Tasks**

- [ ] Get a user's primary email address when using GitHub social sign-in. Solution [seems to be here.](https://github.com/spring-projects/spring-social-github/issues/29)
- [ ] Add user's email address to the user table
- [ ] Add user's name to the user table
- [ ] Mark the email address as verified (we can trust GitHub verifying the users' email addresses)

**Comment by bbenoist** [comment]
It's worth noting that the primary email address can be changed from GitHub. Hence, it's not really something that's expected to be reliable over the time.
We can however use it for some specific and _legal_ purposes but it'd help the technical solution if you give us what you'd like to do with it.

**Comment by nicOwlas** [comment]
Initial purpose was to allow linking accounts. eg: I logged in with magic-link, now I log in with GitHub (same primary email address) show me the same workspaces etc.

1st investigation showed that if from GitHub you had set your primary email address as private then we were not able to get this email address when a user logs in with GitHub. Is it really blocked by GitHub though? Supabase only relies on GitHub and its sends some emails to its users about the billing etc. so it must be possible to get a private primary email address.
