### ISSUE TITLE
Workspace settings page

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#495]
**Tasks**

- [ ] Add workspace settings page
- [ ] ~~Add to workspace entity in DB a URL field (url to the organization picture)~~
- [ ] ~~Store the organization picture on supabase~~

Same mockup as #507 

Blocked by #459
