### ISSUE TITLE
Fix email titles appearing too big on mobile

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#506]
**Problem**
Titles in Sign-up/Sign-in & Invitation emails do not display well on mobile as the font size is too big. Lack of consistencies between emails.

**Tasks**
- [x] Update sign-up email ([mockup here](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3062%3A10031)) to be inline with the sign-in email (Mailjet template)
  - [x] Text was updated (shorten)
  - [x] Title was updated
- [x] Invitation email
  - [x] Update text according to mockup (recipient is notified he/she should not share the email as it is valid for one person only).
- [x] Use same format as in the sign-in email
- [x] Check the 3 emails are inline with the mockup.

![image](https://user-images.githubusercontent.com/16015322/137156352-a1fd4696-019a-4d1f-9331-22705d37b036.png)

**Comment by geoffreyvancassel** [comment]
- [ ] Put the full logo "name + picto" on both emails signin signup
- [ ] replace "Welcome to LabelFlow" by "Build your datasets now !"
