### ISSUE TITLE
Create account settings

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#507]
### Tasks

- [ ] Add account settings page
  - [ ] Add `settings` as a reserved name that cannot be used by a workspace)
  - [ ] Url of the page: https://labelflow.ai/settings/profile
- [ ] Add `Settings` in user menu in the navigation bar
- [ ] Use [Form with shadow](https://pro.chakra-ui.com/components/application-ui/forms). with following edits
  - [ ] Only keep the Name&Avatar section
  - [ ] Remove the buttons change name and change avatar
  - [ ] Replace the name field by a text box with the name pre-filled
  - [ ] Add a Cancel / Save button at the bottom on the right hand side (labelflow-500 for the Save button)
  - [ ] No Breadcrumbs, only LabelFlow logo in the top left.
- [ ] ~~Add to user entity in DB a URL field (URL to the user picture)~~
- [ ] ~~Store the user picture on supabase~~
- [ ] ~~fill the avatar with the picture centered~~
- [ ] ~~If size limit is exceeded, display alert notification~~
- [ ] ~~Send verification email if the user updates his email address~~
- [ ] ~~Mark the email address as unverified until the user clicks in the email~~

### Questions / Remarks
- ~~Unless there is an easy solution, let's skip the modal to crop/reframe uploaded profile pictures~~
- ~~What limit size is reasonable for the picture?~~
- ~~For now, if a user has two accounts (GitHub + Email), if he enters his email address on his GitHub account, we will send a verification email and we would end up with 2 accounts for one email address which is problematic. Need to address merging of account rapidly.~~

### Mockup
[Form with shadow](https://pro.chakra-ui.com/components/application-ui/forms)

![Screenshot 2021-10-14 at 11 07 38](https://user-images.githubusercontent.com/16015322/137287720-5ac5e472-69ca-4f9e-a5f6-70f6e7655b7a.png)
