### ISSUE TITLE
Smart labeling - IOG

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#508]
## Objective

Accelerate labeling by creating polygons around an object from its bounding box

## Tasks
Merge the work on an Auto Polygon feature branch. The feature is hidden behind a feature flag.

### IOG creation

- [x] Polygon geometry is initialized by the bounding box geometry
- [x] Spinner inside the box while iog is running (1st time or improvement)
  - [x] Gif spinner icon in the middle of the donut hole. Chakra has a spinner: https://chakra-ui.com/docs/feedback/spinner. If you can integrate to Open Layers: go for size `md` color `#31CECA`
- [x] Icons. Circles are 32 pixels wide on retina, 16 pixels wide otherwise. Mockups have the correct size if you export them in 1x.
  - [x] Target for the central point. The target can be dragged anywhere inside the bounding box
  - [x] Clicking outside the polygon creates an Inside point which is green (check mockup)
  - [x] Clicking inside the polygon creates an Outside point which is red (check mockup)
  - [x] Mouse icon is a  circle and a `+` when hovering outside the polygon (check mockup)
  - [x] Mouse icon is a  circle and a `-` when hovering inside the polygon (check mockup)
  - [x] Mouse icon is a  circle and a `x` when hovering an inside or outside point (check mockup)
- [x] Clicking on an inside or outside point deletes the point
- [x] We use the same logic for class assignment than bounding boxes or polygons: right click inside the polygon in select mode or in tool mode
- [x] Clicking outside the box (ie inside the donut) triggers following actions:
  - [x] the donut is hiddent
  - [x] the iog geometry is displayed (it's the bounding box before the 1st inference is returned)
  - [x] a spinner spins inside the bounding box so long the inference is not returned by the server (add a timeout after 4sec in any case and display an alert to notify it failed)
  - [x] the user can continue working nominally on the platform (go to another image, create other bounding boxes, polygons, auto polygons etc.)
  - [x] we can delete the bounding box (a polygon geometry more generally) while there is a spinner
- [x] If the inference fails: display a chakra alert
- [x] Increase cache size to store 100 images

### IOG edition

- [x] When you select an Auto Polygon
  - [x] It behaves like a normal polygon (you can edit its geometry)
  - [x] In select mode, a magic wand edit switch appears next to the bin on polygons created thanks to auto polygon (shortcut `e` for edit, if one presses the `a` shortcut then you can create a new Auto Polygon, not edit the currently selected one). Check the [mockup for the magic wand edit icon](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3401%3A19977)
  - [x] When one clicks on the magic wand edit switch, the mode switches from select to Auto Polygon (and the corresponding tool gets highlighted in the tool bar)
  - [x] The donut then is displayed together with the target/inside/outside points
- [x] Possibility to delete / remove the inside / outside points, triggers a new inference
- [x] Possibility to move the target point, triggers a new inference
 
### Productivity
- [x] Use shortcut `a` to activate tool
- [x] Use shortcut `enter` to validate polygon and quit edition mode

### Tools

[Mockup for the tool](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=711%3A8707):
![image](https://user-images.githubusercontent.com/16015322/139036662-aa3528a3-36d9-4678-aaa7-1ff3b1dd6905.png)

[Mockup iog points](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3304%3A22072)
![image](https://user-images.githubusercontent.com/16015322/139243225-adbef569-ba6f-46a6-be78-e897339f0d1a.png)

[Edit Auto polygon](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3401%3A20234)
![image](https://user-images.githubusercontent.com/16015322/139828410-4569a07a-4217-4aec-b92e-1af8c921fffd.png)

Blocked by #518

**Comment by crubier** [comment]
- https://openlayers.org/en/latest/examples/layer-clipping.html
- https://openlayers.org/en/latest/examples/layer-clipping-vector.html

**Comment by etiennedupont** [comment]
@nicOwlas I am not in line with this sentence:

> in select mode, a magic wand edit switch appears next to the bin on polygons created thanks to auto polygon (shortcut e for edit, if one presses the a shortcut then you can create a new Auto Polygon, not edit the currently selected one)

In my opinion, it doesn't make sense to have two modes that overlap this way, let's discuss that during the DSM

**Comment by nicOwlas** [comment]
We rediscussed this with Vincent last Friday and agreed that it makes more sense to stay in select mode to edit and be able to switch easily between iog editing and classical polygon editing.

Another reason is that it's by "chance" that the iog creation and edition have the same ui. It's not the case with the other tools: polygons or bounding boxes and might not be the same with other tools to come. So we keep the same behaviour for all of them: to edit a label, it's done in the select mode.

**Comment by etiennedupont** [comment]
Given your explanations I would expect that we can't add or remove refinement points when we create iog polygons, is that correct?

**Comment by nicOwlas** [comment]
No. We can, it's part of the creation process.

**Comment by crubier** [comment]
Basically a pattern that we already have in several places in the code is something like this:

`const showPolygonEditionTools = (selectedTool === Tools.Polygon) || (selectedTool === Tools.Select && selectedLabel.type === LabelType.Polygon)`

We already have similar things in our code in several places and it makes sense, the "drawing tools" are actually "creation/addition tools", but to modify/edit labels, you have to use the selection tool: to modify boxes or polygons or change classifications for example.

The only thing is that so far, creation and edition are visibily different: creating a polygon is different from modifying it. same for box and classifications. With IOG, the interface for creating and for modifying looks very similar so I understand why you wanted to make it be the very same tool, but conceptually, it is not the same tool. Example: when you click in the donut to finish your iog, in creation mode it should allow you to create another iog label, but in selection/edit mode it should go back to edition mode. 

So doing IOG differently would 1) cause a UX problem because it's not consistent and 2) probably cause additional code complexity down the line because it would be another special case, when we could just do without a special case

**Comment by crubier** [comment]
I think it's fine

**Comment by etiennedupont** [comment]
Understood I'm on it

**Comment by etiennedupont** [comment]
Addressed in #570
