### ISSUE TITLE
End to end tests for online workspaces

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#519]
**Tasks**

- [ ] Add to GitHub actions (check what was done [in this PR](https://github.com/labelflow/labelflow/pull/457/files))
  - [ ] [GitHub Documentation](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers)
  - [ ] Create following tests: https://www.figma.com/file/56hJc9jl9oedCWIfxj7TyU/State-Diagram?node-id=23%3A695
- [ ] Create a test specific DB
