### ISSUE TITLE
Add thumbnails to improve loading time

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#521]
## Tasks

Data upload steps today:
1. `getUploadTarget`: graphql request to know where image should be uploaded
2. request to upload the image
3. create the image in the DB 

- [ ] At upload time, generate image thumbnails of width format: 150/300/600
  - [ ] Create the thumbnails at step 3. and reupload them to the right thumbnail folder.
  - [ ] Maybe replace probeImage by vips (get image dimensions and content type)
- [ ] When an image is deleted, delete also its thumbnails
- [ ] Store the thumbnails on supabase in a thumbnail folder per dataset and in the cache for the local dataset. Each image has the suffix toto/titi/tata.jpeg =>  toto/titi/thumbnails_600/tata.jpeg
- [ ] URLs where images can be changed for thumbnails
  - [ ] https://labelflow.ai/[workspace-slug] Replace the dataset card image by a 300 thumbnail
  - [ ] https://labelflow.ai/[workspace-slug/datasets/images] Replace gallery of images by 300 thumbnails
  - [ ] https://labelflow.ai/[workspace-slug/datasets/images/image-blabla] Replace gallery by 150 thumbnails
