### ISSUE TITLE
Check refetch queries for better performances

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#522]
**Tasks**
- [ ] Check refetch queries, are we doing a refetch after every polygon creation?
- [ ] ~~Paginate the dataset image gallery~~
- [ ] ~~Paginate the gallery in the labeling interface~~

Blocked by #521
