### ISSUE TITLE
Workspace dashboard to follow plan consumption

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#533]
## Tasks

- [x] Add the workspace corresponding tag next to its name
- [x] Create an `imageAggregate` for a given workspace
- [x] Set progressBar to orange (see mockup) when consumption is above 80%
- [x] Set progressBar to red (see mockup) when consumption is above 100%
- [ ] Implement the workspace limits according to the plan

## Mockup ([here](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4223%3A14405))
![image](https://user-images.githubusercontent.com/16015322/152524971-473c5e0e-f623-4e5e-bdb8-8300321b2f59.png)

Depends on #531

**Comment by bbenoist** [comment]
Might help: https://www.npmjs.com/package/@stripe/react-stripe-js
