### ISSUE TITLE
IOG - Create the Auto Polygon tool and alert dialog

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#538]
## Objective

Accelerate labeling by creating polygons around an object from its bounding box.

## Tasks

Merge the work on an Auto Polygon feature branch. The feature is already hidden behind a feature flag. Check with @etiennedupont for details on which one.

### IOG tooling

- [x] Add iog tool to list of tools (`ioColorWandOutline`)
- [x] Notify the user the images will be uploaded to be processed
- [x] Option A: Display an alert dialog
  - [x] Create the alert dialog as per the [mockup](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3397%3A19216) to let the user know he/she understands his images will be analyzed on "our" servers.
  - [x] Store in a cookie the acceptance when user clicks on `Continue`.
  - [x] The alert dialog is displayed only if the tool is selected and there is no cookie.
![image](https://user-images.githubusercontent.com/16015322/139068251-21588221-ac68-4a71-abbe-727da22c60d6.png)

### Canceled options
  - [x] ~~Option B~~: Change the welcome dialog. Some users have already seen it and won't see it again. The message won't be very clear as we state there that no images are leaving their computer
  - [x] ~~Option C~~: have a tooltip next to the tool explaining the image is analyzed on our servers
![image](https://user-images.githubusercontent.com/16015322/139041747-02d05b09-ea36-4ad2-a81c-5e22d9af30e7.png)
