### ISSUE TITLE
Integrate supabase locally and add it to the CI for end to end tests

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#554]
**Objective**
Do not upload test images to the prod DB, create a test DB.

**Tasks**
- [ ] Use Supabase CLI to launch the end to end test DB
  - [ ] See doc: https://supabase.io/docs/guides/local-development
- [ ] Investigate if it can run in the CI

**Comment by nacho-carnicero** [comment]
Closing this, will be treated by #601
