### ISSUE TITLE
Create the /open page

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#593]
## Objective

We are going open 🎉  Lets create a page on the website and share our metrics with the world.

## Tasks

- [ ] Integrate the dashboard as an iframe on the page. `Powered by Metabase` needs to appear (as on cal.com/open)
- [ ] Create the page on labelflow.ai/open
- [ ] Reserve `open` so that it's not reserved by a workspace (I have created a workspace named open to book the name, ask me and I'll rename it when you are doing this task)

## Documentation
- Sequin has some good documentation on how to create this page: https://github.com/sequin-io/open.
- cal.com/open is also great and they are using Metabase as we are
