### ISSUE TITLE
Store Images on AWS

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#599]
## Limitations with current implementation
- Vercel limits file upload to 5MB
- No Supabase CI on Mac

## Options
- Change from NextAuth to Supabase for authentification
  - Need to change Sign in page
  - Need to write RLS rules
- Change storage provider (AWS)
  - Easier

## Tasks option: Change storage provider (AWS)
- [ ] #626
- [x] Create 1 bucket `labelflow-images` on Sterblue AWS
- [x] Organize files similarly than on Supabase (thumbnails and original images)
- [x] Upload connector: test `uploadS3`

## Improvements
- [ ] #631

**Comment by nicOwlas** [comment]
Edit to the issue. We wrote: `Organize files similarly than on Supabase (thumbnails and original images)`. Lets add one level: workspaceId ok? Like that the images will be stored in s3:labelflow-images/workspaceId/datasetId/imageId.

To be investigated by from what I understand: this would allow giving access to the users to their workspace "folder" only if they want to download their data: https://aws.amazon.com/blogs/security/writing-iam-policies-grant-access-to-user-specific-folders-in-an-amazon-s3-bucket/
(with some side effects to be studied: they would be able to list the ids of all the folders inside the labelflow-images bucket)

**Comment by etiennedupont** [comment]
Fixed in #607
