### ISSUE TITLE
Delete a workspace

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#606]
## Objective
Delete a workspace

## Tasks
- [x] Create a `deleteWorkspace` resolver to delete a workspace
  - [x] Add a `deletedAt` to the workspace entity
  - [x] In the workspace switcher, filter the workspaces with a `deletedAt` not `null`
  - [x] Replace the workspace slug by `workspaceSlug-workspaceId`
  - [x] Cancel the Stripe subscription
- [x] Unhide the delete workspace section in the workspace settings tab and link the delete button to the `deleteWorkspace` resolver
  - [x] Confirmation modal to alert that the slug will be released to the public, invoicing section, images etc. will be lost.
- [x] In this issue: do not delete the entities and files of a deleted workspace: it will be done in another issue

## Mockup
- [Settings page & confirmation modal](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3686%3A20094) 
![image](https://user-images.githubusercontent.com/16015322/144291302-9697a714-961c-4c8f-aaef-1a813fe97310.png)

**Comment by nicOwlas** [comment]
UI/UX done
[Settings page & confirmation modal](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3686%3A20094) 
![image](https://user-images.githubusercontent.com/16015322/143914102-a46dc19d-de86-41d6-b0bd-da4b120d0917.png)

**Comment by bbenoist** [comment]
There still remains a functional issue.

After "deleting" a workspace with the `deletedAt` mechanism, a new workspace with the same still name cannot be created.
The DB fails with the following error:

```text
Unique constraint failed on the fields: (`name`)
```

The `Workspace.name` property is required to be unique in DB but the specs of this issue don't ask to change it.

If we still want to keep the `deletedAt` property mechanism, we need to either:

a. Also add the `id` of the workspace at the end of the `Workspace.name` property when deleting a workspace.
    _As for the `Workspace.slug`, I still don't really like that but if we really want unique names (which I find somewhat useless since slugs are the only source of truth in the app) we must stick to this choice because of the combination of the `deletedAt` mechanism and unique `name` and `slug` keys (as explained above)._
    
b. Don't require `name` to be unique in DB and remove it from the "unique" GraphQL filters. We already have `slug` which is the source of truth in the app and should be enough.

c. Reconsider the `deletedAt` mechanism :trollface: 

@labelflow/dev Any opinion?

**Comment by bbenoist** [comment]
@nicOwlas Since we've decided to keep the `deletedAt` mechanism, could you please create the issue for purging deleted workspaces so that we can make sure that we'll be compliant with GRDP before workspaces gets publicly available?
