### ISSUE TITLE
Update dataset class tab

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#623]
## Tasks

- [x] Use Chakra Pro list component. [Mockup here](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3717%3A20156)
- [x] Check compatibility with reordering component
- [x] 5 columns
  - [x] Reordering handle
  - [x] Class color and name
  - [x] Number of occurences (query the labels and count the labels of a given class type)
  - [x] Keyboard shortcut (i: "A keyboard shortcut is available for the first 9 classes")
  - [x] Edit / Remove / Create: triggers the edit / remove / create modals. [Mockups here.](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3717%3A21466)

## Mockups

- [Class List tab](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3717%3A20156) 
![image](https://user-images.githubusercontent.com/16015322/143908927-cd55456a-92c6-432a-af05-4fded52bf91a.png)
- [Edit/Delete modals](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3717%3A21466) 
![image](https://user-images.githubusercontent.com/16015322/143909054-11559818-b213-40c5-9aea-d0c3853c521d.png)

**Comment by nacho-carnicero** [comment]
Closed by #648
