### ISSUE TITLE
Inform end-users about new features, important changes and maintenance

### ISSUE THREAD

**Issue by bbenoist** [labelflow/labelflow#635]
**Is your feature request related to a problem? Please describe.**

AFAIK, we have no way to inform our end-users that new features are available.

**Describe the solution you'd like (import visuals when possible)**

If relevant (new page load && new release  && not already dismissed && ), either (supporting both might be needed):

## Tasks

- [x] Integrate announcekit to labelflow.ai: (credentials are on 1password/LabelFlow)
  - [x] React component:  https://announcekit.app/docs/reactjs
  - [x] Widget code in `Widgets/Modal/Implementation`
  - [x] Replace the What's new by a bell icon

## Similar tools
```

* open a modal which summarises the latest features
    ![image](https://user-images.githubusercontent.com/2091902/144844192-bad1064e-692f-473b-b3fd-22f9c4246e01.png)

* display a tooltip next to new components
    ![image](https://user-images.githubusercontent.com/2091902/144844906-4c444fd2-071b-404e-ae5f-ad87e663a3de.png)

And always provide a (`target="_blank"`) link to the details (either on a dedicated page or on GitHub Releases).


**Describe alternatives you've considered**

Not really alternatives but complementary:
* Email
* Blog post
* Tweet
```

## Blocked by

Blocked by https://github.com/announcekitapp/announcekit-react/issues/27

**Comment by RaynalHugo** [comment]
Here is what we used at Sterblue: https://announcekit.app/

**Comment by bbenoist** [comment]
@nicOwlas It looks like that we can't customize the style with the current plan: 
![image](https://user-images.githubusercontent.com/2091902/149193970-9183f1c6-ce5b-44e6-882a-711dbaca0c00.png)

**Comment by bbenoist** [comment]
@nicOwlas I've started to work on integrating the AnnounceKit React component:

https://github.com/labelflow/labelflow/pull/787


So far, it's not been that simple:
* I can't use the default Widget icon in the top-bar since it won't fit our Chakra design

* The booster is adding a margin to the top of the whole page but does not uses it:
![image](https://user-images.githubusercontent.com/2091902/149277966-90692ce1-1a84-4ad9-a94c-a2cb9ec3f853.png)

* On mobile, the booster close button is not visible (it only shows up if we open then close the details).

* In-order to reuse the correct types from the library without duplicating code, I've had to open a PR on announcekit-react: https://github.com/announcekitapp/announcekit-react/pull/25

* The React component props are not fully-typed. Every functions are typed with `Function` and the core widget instance is `any` so I had to dive into other implementations to make sure that I wouldn't make incorrect assumptions. I've also had to include such checks in my code: 
  ```ts
  if (unread === undefined || typeof unread === "number") {
    return unread;
  }
  // We don't want to crash the whole application because of AnnounceKit
  // poorly-typed component props.
  ```

* I had to make an IconButton component so that we won't have to duplicate our own customization of the Chakra component (tooltip + some props + react-icon wrapper) everywhere in the code just for something which should have been included inthe library.

___

Current preview: https://labelflow-3lil1o277-labelflow.vercel.app/website

## App

* I've still have to make the red bubble disappear on the page we just have read announcements (i.e. no refresh when opening the widget)
* I've used a megaphone icon because it's not really notifications but announcements. It's not the same We'll eventually change it once we implement the collaborative features.

![image](https://user-images.githubusercontent.com/2091902/149275340-a149377b-42a4-458a-831d-e2c673fa10b9.png)
![image](https://user-images.githubusercontent.com/2091902/149275473-ae40dcca-4434-40c2-9e65-cb115078790c.png)

## Website

* I've used a rocket since it should only show positive announcements on the website (isn't it)
* I still need to make the whole bar vertically centered so that the icon and text are correctly centered
* I still have to add the red bubble on the desktop version

### Desktop

![image](https://user-images.githubusercontent.com/2091902/149299324-3d9e5b10-7801-42ae-9d02-eab2b5c28ab8.png)

### Mobile

![image](https://user-images.githubusercontent.com/2091902/149304333-d3a567dd-7e9a-4109-8abf-e59d2f3af1d1.png)

**Comment by bbenoist** [comment]
@nicOwlas After looking at it again, I think that the website desktop component should be aligned to the right (i.e. at the left of the `Star us on GitHub` button).

**Comment by nicOwlas** [comment]
Sad that the integration is as painful...! For the website, I would not put any icon. We see announcement icons on apps but on websites it's not something I've seen in the past. Good for the speaker icon 👍

**Comment by bbenoist** [comment]
OK fine for the website icon! It makes the things easier.
As for the red unread bubble, I'm not sure yet if it's pointful on the website 🤷‍♂️

**Comment by nicOwlas** [comment]
For the website, the only thing which may be useful is to add booster bar at the top to notify about webinars or other events. So I would remove unread bubble entirely.
