### ISSUE TITLE
Paginate the image gallery tab

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#660]
## Objective:
Paginate the image gallery tab to have a smooth loading even on large datasets

## Tasks:
  - [x] Display pages of X elements with X = 50/100/1000 is a good compromise to avoid the complexity introduced by infinite scrolling for now.
  - [x] Page selector is similar to the image selector on the labeling view
  - [x] Segmented controls are used to select the number of items per page
  - [x] We display the index of items displayed. It does not correspond to the items selected. Page 10 with 50 images per page we would display `501-550 of 720`
  - [x] The bottom bar does not scroll, it's always visible. This allows to not have to scroll to the bottom of the page or back up to change the page.

## Mockup ([link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4008%3A13848))
![image](https://user-images.githubusercontent.com/16015322/147340214-9b2b6ebf-10a3-441c-96fd-0ddb793a7fb3.png)

**Comment by nicOwlas** [comment]
Regarding pagination of images: [see conversation here](https://labelflow.slack.com/archives/C022Q91MGCX/p1639667305015900)

**Comment by nicOwlas** [comment]
Mockup for validation (issue description updated) ([link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3962%3A14943))
![image](https://user-images.githubusercontent.com/16015322/146969081-6203b934-cc12-4254-8a90-82a82ff2b53d.png)

**Comment by valerian** [comment]
@nicOwlas do we want pages to have their own URL?

**Comment by nicOwlas** [comment]
> @nicOwlas do we want pages to have their own URL?

Not for now. I can't identify a use case where it would be useful. Also the other platforms mentioned[ in this thread](https://labelflow.slack.com/archives/C022Q91MGCX/p1639667305015900) are not doing it.

**Comment by crubier** [comment]
Me when I see the pagination interface

![5dbpp5](https://user-images.githubusercontent.com/2954572/147264566-8a03fcc0-8249-41f4-a625-ba0b4cbaae02.jpg)

**Comment by nicOwlas** [comment]
> Me when I see the pagination interface

Opened to suggestion

**Comment by nicOwlas** [comment]
Some alternative designs

- 
![image](https://user-images.githubusercontent.com/16015322/147270927-302a1c95-6215-46ac-9f27-c17003aea125.png)
- 
![image](https://user-images.githubusercontent.com/16015322/147270895-1c83c760-9a77-4712-95bc-cb5a8413621e.png)
-

**Comment by crubier** [comment]
> Opened to suggestions

You know me, I like my infinite scroll, and dislike pagination, it feels so 2002 to me. 

We perceive that pagination is common because we see it in many places. But actually we only see it because it's an eyesore. On the other hand, we don't see infinite/virtual scrolling even though it's everywhere: Slack messages, Airtable rows, Google Drive, Excel lines, Github comments, Facebook feed, Twitter feed, VSCode editor (in the 80s you had pagination on text files on some editors...) , etc.

About the constraints:

- No infinite scrolling
  - Why? Pagination and infinite scrolling are exactly the same on the server side. And on the client side I think having the paginator interface is as complex as having an infinite scroller. At Sterblue we did paginated virtualized grouped lists which was much more complex.
- Be able to change the number of items per page
  - If there wasn't pages, you wouldnt need a control to change the number of items per page
- A dataset could have hundreds of pages, we need a way to quickly skip pages / go to a specific page
  - Did a user ask for that ? I'm pretty sure user need to be able to go to a specific image (hence the image index navigator which exists already in the image labelling interface, and which could exist on an infinite gallery), but I'm not sure a user would ever actually want to go to a specific *page* (especially if there is no concept of page..) What they really want is to go to an image index
- We should be able to change page without needing to scroll to the bottom
  - Yes, if you have pages, I agree
- We will soon have bulk actions at the top above the gallery cards (select all, delete etc.)
  - Then there is always the annoying thing with pagination + bulk actions: do the bulk action only apply to the current page ? I have PTSD from managing epics page by page on github, having to run the same bulk action over and over again on each page. On Airtable you do it once, it's logical.
  
Personally If I had to pick between your designs, I would say something like

- The white bar like your last example
- previous / next / index in the middle like your last example
- But with the number of items per page being on the bottom right, and with a dropdown menu or something, (The segmented button is too much UI for an anecdotic functionallity). As Steve jobs said: Content first, the UI shouldn't get in the way
