### ISSUE TITLE
I'm being apparently signed out after getting an error on the labeling view.

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#681]
**Describe the bug**
I'm being **apparently** signed out after getting an error on the labeling view on an online workspace (the image won't open though it's thumbnail is showing up in the image gallery tab). The sign-in button appears on the error page.

When clicking on the LabelFlow logo in the top left corner, I come back to my workspace and I'm signed in.

**To Reproduce**
1. Connect to: https://labelflow-jv1txv40y-labelflow.vercel.app/demo/datasets/large-dataset (accessible to the user engineering@labelflow.ai)
2. Click on the first image in the gallery: https://labelflow-jv1txv40y-labelflow.vercel.app/demo/datasets/large-dataset/images/0b9aef91-64a6-4514-a60a-e4962ce10195
4. See error screen and notice that the sign-in button appears
5. Open the debug info. You'll see your initials in the top right corner as if you were logged in. By clicking on the LabelFlow logo, I can go back to the datasets in my workspace. Which shows I wasn't effectively signed out.
- Likely cause: the authentification query fails because there are too many connections to the DB

**Expected behavior**
I should not appear as signed out. Signing back in fails as I'm not effectively signed out.

**Tasks**
Only the 1st task described in Nacho's below comment is part of this issue:
```
There are two different problems in this issue which in my opinion should be tackled in two separate issues.

The first one is that the ErrorBoundary component does not have access to the right environment in order to get if the user is signed in or not. See how we pass an undefined session to the ErrorFallback component in here typescript/web/src/pages/_app.tsx. If we can't pass properly a session to this fallback component then the best solution would be to remove the top bar (or at least the user part) in it, but we could try before to pass the session in props (if it's not possible with the ErrorBoundary component from react-error-boundary we could implement our own error boundary component (see how to do that in the React docs).
``` 

A separate issue will eventually be opened for the 2nd part (ie display a specific error screen for max connection errors).

**Screenshots**
![image](https://user-images.githubusercontent.com/16015322/147118948-c59891bd-9c83-4a86-8c6b-9589b95d7e31.png)
```
    LabelFlow

    Debug

Debug information
Links:

    Link to Github issue tracker
    Link to Sentry error tracker
    Link to Clarity usage analytics
    Link to client bundle analysis
    Link to server bundle analysis
    Link to Graphiql
    Link to Database admin
    Link to CMS admin
    Link to Github branch
    Link to Github commit
    Link to Vercel deployment
    Link to CMS deployment on Heroku
    Link to mailer provider

Client environment:

{
  "clientType": "Standard LabelFlow Client App",
  "isInWindowScope": true,
  "isInServiceWorkerScope": false,
  "isDevelopmentEnvironment": false,
  "browser": {
    "name": "firefox",
    "version": "95.0.0",
    "os": "Mac OS",
    "type": "browser"
  },
  "env": {
    "NODE_ENV": "production",
    "NEXT_PUBLIC_VERCEL_ENV": "preview",
    "NEXT_PUBLIC_VERCEL_URL": "labelflow-jv1txv40y-labelflow.vercel.app",
    "NEXT_PUBLIC_VERCEL_GIT_PROVIDER": "github",
    "NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG": "labelflow",
    "NEXT_PUBLIC_VERCEL_GIT_REPO_OWNER": "labelflow",
    "NEXT_PUBLIC_VERCEL_GIT_REPO_ID": "366659969",
    "NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF": "feature/workspaces",
    "NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA": "a26a3e4062ea2bbe5752ff0f31d0e049e1df0baf",
    "NEXT_PUBLIC_VERCEL_GIT_COMMIT_MESSAGE": "Merge pull request #669 from labelflow/security/bump-graphiql-version\n\nUpdate graphiql version",
    "NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_LOGIN": "RaynalHugo",
    "NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_NAME": "Hugo Raynal",
    "NEXT_PUBLIC_IOG_API_ENDPOINT": "https://iog.labelflow.net/graphql/"
  }
}
Server environment:
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nacho-carnicero** [comment]
There are two different problems in this issue which in my opinion should be tackled in two separate issues.

The first one is that the `ErrorBoundary` component does not have access to the right environment in order to get if the user is signed in or not. See how we pass an undefined session to the `ErrorFallback` component in here `typescript/web/src/pages/_app.tsx`. If we can't pass properly a session to this fallback component then the best solution would be to remove the top bar (or at least the user part) in it, but we could try before to pass the session in props (if it's not possible with the `ErrorBoundary` component from `react-error-boundary` we could implement our own error boundary component (see how to do that [in the React docs](https://reactjs.org/docs/error-boundaries.html)).

The second problem is that sometimes we appear to be signed out due to the fact that we have reached the max DB connections. If this is the problem we should be able to catch it in the client side and inform the user that the platform is momentarily not usable. So we should:
 - [ ] be able to catch the max DB connections issue on the client
 - [ ] create a page to inform the user the platform is not usable at the moment
 - [ ] display that page when we get a max DB connections error
