### ISSUE TITLE
Prioritize loading of current image on Labeling view. And cache-first policy for the already preloaded images

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#718]
## Objective
Following Vincent's feedback [here](https://labelflow.slack.com/archives/C022PCC0H0W/p1640896185421100):
- Next and previous images are loaded in parallel with the current images which increases the time before one can start labeling

## Tasks
- [x] On the labeling view, prioritize the loading of the current image over its neighbors
- [x] When navigating to the next or previous image, do not reload the already loaded images
- [x] Image and graphql cache-first policy to quickly display the already loaded images and their graph data.

## Potential problem
- If image URLs are signed, the browser will not know it already loaded the image (look for sign URL image cache to find potential solution)

## Investigation
- Check if the url can be used more than one time ? If yes put the URL in the appolo cache
