### ISSUE TITLE
Drop Service Worker

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#741]
## Objective

The service worker is cool to have an app not relying on an online backend and keep the images locally stored. Nevertheless, it adds a layer of complexity which slows the development of LabelFlow's main features.

The goal of this issue is to remove the Service Worker while still keeping a smooth onboarding experience. For the image privacy considerations, the on-premise version of LabelFlow will fill the gap.

### User story - No login required
- User clicks on try it now
- He visualizes the tutorial in his `Personal-[uniqueId]` workspace
- Similarly to the local workspace:
  - Settings are disabled
  - Member page does not allow him to invite people

### Technical questions/difficulties
- We need to create a user & membership in the DB with no prior
- How to display the same personal workspace to the same user everytime. JWT will do the job so long it is not cleared right?
- Need to store a sessionID

### User story - Simplicity
- User clicks on try it now
- Workspace creation modal appears
- Login modal appears
- Tutorial dataset is shown in his newly created workspace
- Workspace is initiated with the community plan
- No need for a specific workspace

## Tasks

- [ ] Remove the service worker code
- [ ] Warn users that their local workspace will be replaced by a personal workplace.
- [ ] Have an home page to redirect to it when one deletes a workspace
  - Excalidraw redirects to the user page
  - We should redirect to another workspace the user is member of
  - If no other workspace, show an empty state with a call to action to create a workspace

## It will allow
- Import: Optimize thumbnail generation
- Optimize DB: focus on Prisma and do not consider Dexie
- Clean typing with specificities due to Dexie
- iog can be used only if the user is signed-in
- Simplify architecture

## Mockup

Workspace empty state page ([link here](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4131%3A14296))
![image](https://user-images.githubusercontent.com/16015322/148402446-50e51f0e-bcb0-4ed0-bc9b-4f624ff9886b.png)

**Comment by bbenoist** [comment]
For the fun (we all have some dirty passions 😜), I've spent an hour removing most of the files specific to the SW (120 files removed, added or modified as of now 🔥).

You can see the result in #748

As of now, `yarn dev:web` is running and I've got most of the app working. I've also built a _quick & very dirty_ `/` homepage which lists workspaces and have a "New workspace" button so that we can start working in parallel with the removal 🚀 

The biggest challenges I see so far before we can merge the changes are (by order of priority):

- [ ] 🌶️ [Mock Apollo Client in Jest tests for web](https://www.apollographql.com/docs/react/development-testing/testing/). _You can see an improvable example in the [`CreateWorkspaceModal` fixtures](https://github.com/labelflow/labelflow/blob/b52fae9ef1b05e78731eedbe7099168a79e187b9/typescript/web/src/components/workspace-name-input/workspace-name-input.fixtures.tsx#L24) I've recently made._
- [ ] 🌶️ Fix the remaining Cypress code based on the SW or Dexie.
- [ ] 🍏 Clear and ignore the `lastVisitedWorkspaceSlug` cookie if its value is `local`.
- [ ] 🍏 Make sure that the workspace switcher doesn't [returns `local` when no workspace can be loaded](https://github.com/labelflow/labelflow/blob/85871c7074f61d1792a97585bdd78ec4d53e9056/typescript/web/src/components/workspace-switcher/workspace-switcher.tsx#L70)
- [ ] 🍔 Make a nice and pointful homepage
- [ ] 🍔 Find a new way to get our users started (as the old tutorial dataset injection cannot be used anymore)
- [ ] 🌶️ Implement a migration feature if its worth it (evaluate with analytics?) or implement #634 
- [ ] 🍏 Make sure that we're compliant with GDPR (=French RGPD). _Do we have a link to a "Terms of service" and a "privacy policy" page?_

Not critical for this issue but blocked by the above points:

- [ ] 🍺 Simplify the architecture (i.e. merge `data`, `common-resolvers`, `graphql-types` and `db`)
- [ ] 🍺 Secure IOG access
- [ ] 🍺 Optimize thumbnail generation

Not _blocked-by_ but somewhat linked to the issue:

- [ ] 🌶️ Implement workspace (_with a `deletedAt` value_) garbage collection (since we will have way more "useless" workspaces)

#

> **Classification:**
> 🌶️ painful | 🍔 needs specs | 🍏 easy | 🍺 fun

**Comment by crubier** [comment]
Cool, it's a good idea to remove it, as I mentioned in November the duplication of effort and code is not really worth it, especially now that online workspaces are a thing and given the size of the team, focus is key.

I agree with most of what you say @bbenoist , I'd just add a couple (big) points:

- [ ] 🌶️  We'll probably need to add many optimistic responses and image preloading now to make online things as smooth as SW ones. The Service worker had the nice property of being almost instant for queries and image serving. (It's something we'd have to do anyway, but removing the SW makes it high prio)
- [ ] 🌶️  Just be careful about the new User onboarding story, and ensure performance is great especially for new users (right now query and image loading are pretty slow-ish but there's a lot of room for optimization)
- [ ] 🍔 Probably add a specific onboarding flow to avoid the "wall of modal" nightmares (Click "try it" => Labelflow Login modal => OAuth provider login modal => Workspace Creation modal). Find a way to make it nicer than that

**Comment by bbenoist** [comment]
Remaining stuff:
- [ ] WIP - #848
- [ ] WIP - #777
- [ ] WIP - #877
- [ ] #883
- [ ] Observed some error 400 with /api/download (already on main?)
- [ ] Make `/local` show an appropriate error message about local workspaces which have been removed.

# Can be fixed into main (remarks from the latest live-review)
- [ ] #876
- [ ] #805
- [ ] Test fixes and cleanup
  - [ ] Stories related with mock-image-loader are still broken
  - [ ] Some stories are missing (e.g. `DeleteDatasetModal`)
  - [ ] Reuse `renderTestWrapper` whenever possible.
  - [ ] Avoid the need to call `mockWorkspace` and `mockRouter`
  - [ ] Factorize and harmonize Cypress tests (should fix flakyness)
  - [ ] Find a way to test `refetchQueries` and remove the corresponding message
- [ ] Remove duplicate CREATE_WORKSPACE_MUTATION query declaration
- [ ] Remove useless? client.query in import-images-modal
- [ ] Use APP_NAME in all `Meta title="LabelFlow ..."`
- [ ] Make /accept-invite reuse useUser instead of using GET_USER_ID
- [ ] Refine `tsconfig.build.json` excludes to only exclude specific directories instead of `**/src/utils/xxx`

**Comment by nicOwlas** [comment]
Remaining issues were grouped into a milestone (together with above comment description)
