### ISSUE TITLE
🌶️  Mock Apollo Client in Jest tests for web

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#771]
## Description

From @bbenoist:
You can see an improvable example in the [CreateWorkspaceModal fixtures](https://github.com/labelflow/labelflow/blob/b52fae9ef1b05e78731eedbe7099168a79e187b9/typescript/web/src/components/workspace-name-input/workspace-name-input.fixtures.tsx#L24) I've recently made.

## Tasks
- [x] Base setup of Apollo mocked provider
- [x] Rewrite Jest tests and Storybook stories
  - [x] Datasets
  - [x] Label Classes
  - [x] Export modal -> #836 
  - [x] Labeling tools -> #842
  - [x] Workspace switcher / create workspace
  - [x] Import button/modal -> #838
  - [x] Hooks -> #841 
  - [ ] Undo store -> #867
- [ ] General testing and cleanup
- [ ] Make sure that everything compiles and tests are ok

(Draft) List of files that should most probably become obsolete and removed in the cleanup phase:
- `web/src/utils/setup-local-db-tests.ts`867

**Comment by bbenoist** [comment]
Closed by #843
