### ISSUE TITLE
🍔  Make a nice and pointful workspace homepage

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#775]
## Tasks
- [ ] Number of workspaces
- [ ] Search by workspace name (and any part of the name, if I write Bourgogne, Enedis Bourgogne would display)
- [ ] List the workspaces by alphabetical order
- [ ] + New workspace displays the workspace creation modal
- [ ] Column plan: display a [chakra tag](https://chakra-ui.com/docs/data-display/tag) for each kind of plan
- [ ] Page accessible on labelflow.ai/

## Mockup
![image](https://user-images.githubusercontent.com/16015322/149927254-3a31aaa8-59b7-49cc-9412-2e24458c9c83.png)

🌶️ painful | 🍔 needs specs | 🍏 easy | 🍺 fun

**Comment by Jordanlelay** [comment]
Depends on #771

**Comment by bbenoist** [comment]
Closed by #843
