### ISSUE TITLE
🍔  Find a new way to get our users started (as the old tutorial dataset injection cannot be used anymore)

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#777]
## Tasks

- [x] Create the tutorial dataset in every newly created workspaces
- [x] Create the empty workspace state
- [x] Remove the welcome modal

Quick win:

- [x] Do not generate the thumbnails

Better:

- [ ] Provide the thumbnails URL
- [ ] Specify the width and height of every external thumbnails

### User story ([link](https://www.figma.com/proto/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?page-id=141%3A36&node-id=4158%3A50222&viewport=404%2C48%2C0.21&scaling=contain&starting-point-node-id=4158%3A50222&show-proto-sidebar=1))
https://user-images.githubusercontent.com/16015322/149919276-56b89d72-18d8-4abb-9b3b-f17aa1634a37.mov

### Workspace empty state ([link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4159%3A14041))
![image](https://user-images.githubusercontent.com/16015322/149919681-6888170a-4e24-422e-9f82-a9836b46ad78.png)

blocked by #806 #776 

🌶️ painful | 🍔 needs specs | 🍏 easy | 🍺 fun

**Comment by bbenoist** [comment]
Closed by #869
