### ISSUE TITLE
Store in a cookie the last visited Workspace ID

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#805]
blocked by #843 

# Tasks

- [ ] When visiting a workspace: check if the workspace id is the same or not than the one in the cookie. If different, update it.
- [ ] When signed-in and going to labelflow.ai/
  - [ ] redirect the user to the last visited workspace or the list of workspaces if there aren't any cookies.
  - [ ] Don't redirect if it's not the same account but the same cookie
- [ ] Ignore `lastVisitedWorkspace` cookie

**Comment by bbenoist** [comment]
Closed by #892
