### ISSUE TITLE
Create home page listing the workspaces

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#806]
## Tasks

- [ ] To be done in another issue ~~Hyperlink to go back to the website~~
- [ ] Number of workspaces
- [ ] Search by workspace name (and any part of the name, if I write Bourgogne, Enedis Bourgogne would display)
- [ ] List the workspaces by alphabetical order
- [ ] + New workspace displays the workspace creation modal
- [ ] Column plan: display a [chakra tag](https://chakra-ui.com/docs/data-display/tag) for each kind of plan 

## Mockup ([link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=3337%3A19162))

![image](https://user-images.githubusercontent.com/16015322/149914702-c9207bd9-bcd7-4faa-a9b4-1747b29446ee.png)

**Comment by nicOwlas** [comment]
Duplicate of #775
