### ISSUE TITLE
Error pages to handle not having access to workspace or dataset page

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#807]
## Context

Display a proper page when a user try to access a workspace he/she has not access to (or when the workspace/dataset slug is wrong.

The request access button is interesting in a second step

## Task

- [ ] Display the [404 screen](https://labelflow.ai/404) when
  - [ ] workspace/dataset slug does not exist
  - [ ] user has not access to workspace/dataset

**Comment by bbenoist** [comment]
@nicOwlas We've groomed some mockups on Figma (below the "workspace flow") so that we can start working on it if we have enough bandwidth while waiting for cross-issues dependencies in "Drop SW" and "AI Assistant".

First, we would just have a "Back to homepage" button:

![image](https://user-images.githubusercontent.com/2091902/150558926-fc8fbd19-2021-4e47-ac4c-70d9edc7019f.png)

Then, once we have finished the service-worker priorities and once you'll be back, we could groom a "Request access" button instead:

![image](https://user-images.githubusercontent.com/2091902/150559016-4854f988-f855-43d6-8af6-28b65c22e515.png)

Can you tell us if you're OK with the 1st screenshot so that we could maybe implement it next week?

**Comment by nicOwlas** [comment]
Good for the icon 👍 and the back to home page. For the text, I would keep the same text for urls existing vs not existing:
> Page not found
> If this page exists ask one of its owners to grant you access

**Comment by bbenoist** [comment]
We already have a page for 404 errors: https://labelflow.ai/404

About whether we should differentiate unauthorized access from 404, I'd say that it depends of the confidentiality level we'd like to have. It does not really proves anything but knowing that a company has a workspace or dataset hosted in our service can already be considered as a security leak.

I doubt that there is a common good practice for this. I've seen very big apps such as JIRA having the `Request access` feature (_hence leaking the fact that the project exists_) and others like GitHub which just shows the 404 page IIRC.

If we don't want to differentiate it:
- [ ] Replace the page asking for a user to be signed-in to access the resource by a redirection to `/404`
- [ ] Redirect to `/404` if the user is not authorized to access the page

If we want to differentiate it:
- [ ] Implement the mockup we've made as a first step
- [ ] As a second step, implement a `Request access` button (_which can be very useful with big companies_). _Detailed below._

The `Request access` button is not really an hard feature to implement but it'd require ~2 days and it's not a priority IMO. Anyway, here is an overview of what it'd need:

- [ ] Show a `Request access` button when an end-user is signed-in but don't have access to a resource.
- [ ] When the `Request access` button is clicked, send an email to the resource owners.  
  Mockups can be defined for the MJML but we can imagine that the email would include  2 buttons `Allow` and `Deny` which would redirect to `/authorize?token=${token}&action=allow` or `/authorize?token=${token}&action=deny`.  
  Il would also have a fallback URL _(in case the buttons don't work)_ pointing to a `/authorize?token=${token}` page with the same 2 `Allow` and `Deny` buttons as in the email.
- [ ] Implement the `/authorize?token=${token}` page which will should grant access to a given user to the desired resource if `action` is in the query params or show the `Allow` and `Deny` buttons otherwise.
- [ ] Once the authorization decision has been made, send an email to the authorized used with a link to the resource it got granted access to.

Until we implement the `Request access` button, redirecting to the 404 page would be sufficient.
