### ISSUE TITLE
Implement AI Assistant

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#811]
# Tasks

## Front
- [ ] Add AI Assistant tab to Datasets
- [ ] List AI assistants and call to action to add an assistant
- [ ] Create cards for assistants (same design as the export cards)
- [ ] Create the AI Assistant selection modal (stack navigator)
- [ ] Create the AI Assistant description card (description on the left, options to the right)

## Back
- [ ] Implement authorship (user or assistant)
- [ ] Create a new assistant entity (endpoint address + key, assumed return format (coco, roboflow, else), options stored as a json?)
- [ ] Create a many to many assistant_dataset table to link datasets and assistants. Add a column to store the assistant options there?

## Questions
- [ ] How to trigger assistants on newly uploaded images?

**Comment by bbenoist** [comment]
```ts
type AssistantType = {
}

type Assistant = {
}

type AssistantConfig = {
}
```

**Comment by bbenoist** [comment]
Before we go deeper in the design specs, here is the type of the `AiAssistant` which can be used to build the GUI and create fake data:

```ts
type AiAssistant = {
  id: string;
  // component: StringInput
  name: string;
  // Very short summary
  // component: StringInput
  summary?: string;
  // Written in Markdown
  // component: MarkdownInput
  description?: string;
  // Image hosted on a specific bucket with public access
  // component: AvatarInput
  iconUrl?: string;
}
```

With this type, devs should be able to start right now building the `AddAiAssistantModal` and the `ConfigureDatasetAssistantsPanel` React components (except for the "variables" part which I'll specify next monday).  
Using dedicated Storybook stories could be a good start 😉 

If needed, the GraphQL and Prisma parts of this entity can already be implemented but don't forget that an `Assistant` is the top-level entity which we'll define. It's not an `AiAssistantTemplate`, nor an `AiAssistantConfiguration` (which I still have to refine).

Just in case I miss specifying everything next monday and it's needed by someone else, here is the rest of the model I've started writing. But keep in mind that it's not definitive yet. I still have a doubt about whether it's useful to have such a flexible model (which comes at the price of complexity)...

```ts
type AiAssistant = {
  // ... + props above
  templateId: string; // Allows to configure a single service (e.g. one for Roboflow) but multiple assistants
  values: Record<string, JSON>;
}

type AiAssistantTemplate = {
  id:string;
  name: string;
  iconUrl?: string // This is te little LabelFlow / RoboFlow icon you can see in the mockups
  // Variables defined here will be reusable in the properties below.
  variables?: Record<string, JSONSchema>;
  url: string;
  params?: Record<string, JSONSchema>;
  body?: JSONSchema | "image"; // image will make the executor sending the image binary as body
  // May differ depending on the remote API
  method?: "POST" | "PUT" | "GET" = "POST";
}

type DatasetAiAssistantConfig = {
  id: string;
  aiAssistantConfigId: string;
}

type AiAssistantConfigValue = {
  id:string;
  parentId: string; // Can be the id of an AiAssistant or an DatasetAiAssistantConfig
  key: string;
  type: VariableType;
  value: string; // JSON value
}
```

Example data for an `AiAssistantTemplate`:

```json
{
  "name": "Roboflow",
  "variables": {
    "apiKey": {
      "title": "API Key",
      "description": "Roboflow API Key (at the end of the Roboflow example URL)",
      "type": "string"
    },
    "minConfidence": {
      "title": "Minimum confidence",
      "type": "integer",
      "minValue": 0,
      "maxValue": 100,
      "default": 40
    }
  },
  "url": "https://detect.roboflow.com/${datasetSlug}/${versionNumber}",
  "body": {
    "api_key": "${apiKey}",
    "image": "${imageUrl}",
    "minConfidence": "${minConfidence}"
  },
  "method": "POST"
}
```

**Comment by bbenoist** [comment]
@nicOwlas Some remarks while I'm adding specs

* I think that we don't need an Ai Assistant tab in the dataset page. I should be a section in the dataset settings page instead. i.e. Below the rename section and above the danger zone.
* My model don't include `Labels created by an AI Assistant are drawn with dash lines and not plain line.` yet as it can be done differently depending on how we solve the owneship questions.
* We've discussed about inner-steps which would allow to publish the features in multiple successive releases: [details are here](https://labelflow.slack.com/archives/C022Q91MGCX/p1643031201056400)

**Comment by bbenoist** [comment]
After discussing it, below are the phases we'll try to follow.

Please not that it don't take the "automated batch-labeling" into consideration as it needs us to resolve the ownership considerations and because it has great chances to cause lambda functions timeout issues (_see #823 for solutions with long jobs_).

## 1 - Static AI assistants
### DB

- [ ] Add a list of the `AiAssistants` we should "hardcode".
  _See `AiAssistant` and `AiAssistantTemplate` models and the example JSON above._

> `AiAssistant` entities aren't stored in DB, the list is just something like `const AI_ASSISTANTS: AiAssistant[]`

### GraphQL backend

- [ ] Implement a `runAiAssistant` mutation which creates and returns the new labels. #823 

### GUI

- [ ] Implement the Ai Assistant  tool in the labeling view.

> * We actually don't even need the dataset settings page at this step
> * No datasets configuration page
> * No "automatically labelize" toggle (_since it needs ownership management_)
> * No way to add, delete or configure an assistant (_hence no pretty list and details page yet_).

## 2 - Add/Delete and Configure `AiAssistants`

### DB
- [ ] Implement the entities and columns required for the `variables` property of `AiAssistantTemplate` to work.
- [ ] Add an entity which links `AiAssistant` with `Dataset` (can we also do it at a Workspace level?)

### GraphQL backend
- [ ] Make `runAiAssistant` interpolate the values when needed

### GUI
- [ ] Create a datasets Ai Assistant settings zone
- [ ] Add/Delete Ai Assistant (_with the "marketplace" list and assistant details page_)
- [ ] Allow to configure Ai Assistants (_either JSON or generated from JSON schema_) from the `variables` definition.
- [ ] Add a Roboflow Custom AiAssistant (_it'll be an AiAssistant with all the inputs exposed as variables_)

## 3 - Dataset/Workspace-wise custom `AiAssistant` and `AiAssistantTemplate`
### DB
- [ ] Add the `AiAssistant` and `AiAssistantTemplate` entities and implement the needed CRUD GraphQL endpoints.

### Backend

### GUI
- [ ] Allow to create new `AiAssistantTemplate`
- [ ] Allow to create new `AiAssistant` from an `AiAssistantTemplate`

## 4 - Public custom `AiAssistant` and `AiAssistantTemplate`

**_Specs TBD as it implies some sort of app-wise administration_**

**Comment by bbenoist** [comment]
While I'm working on it, there is also a very important part that still has to be specified in details: **post-processing**.  

The solution we will implement depends on how the most common AI assistant API differs.  

If it's always the same typical response, we could imagine asking to define a Output->Label mapping as if we'd have call [_jq_](https://stedolan.github.io/jq/) to retrieve values.
But I doubt it could support complex outputs as this solution already fails at the `className`<->`classId` relation ; i.e. what if we must resolve the ID of a class stored in a separate list in the result JSON?

As of now, I'm starting to think that the only pragmatic solution is to add an `outputType` enum property to the `AiAssistantTemplate` entity so that `runAiAssistant` could choose which post-processing it needs to apply.  
In other terms, we'd have:

```graphql
enum AiAssistantOutputType {
  LabelFlow,
  RoboFlow
}

type AiAssistantTemplate {
  outputType: AiAssistantOutputType!
  # +other properties already specified above
}
```

For phase 1, it should not be needed yet but that's something we'd have to think when working on phase 3.

**Comment by Jordanlelay** [comment]
Regarding the Hugging Face investigation I did yesterday (asked by @nicOwlas):

- I have tested it with several [object detection models](https://huggingface.co/models?pipeline_tag=object-detection&sort=downloads), essentially the Facebook ones.
- API is a simple POST route with a token in the headers and the image in the body
- The documentation says the image must be passed as a "[binary representation](https://api-inference.huggingface.co/docs/node/html/detailed_parameters.html#id43)", but a URL pointing to an image **works as well**.
- No other parameters are allowed
- The image size is 10Mb max, bigger will return a `413` status code
- If you try calling a model that is not actively used on Hugging Face, it will return a `503` status code will loading it
- There is no rate limiter on the API
- The return is a JSON [with few specifications](https://api-inference.huggingface.co/docs/node/html/detailed_parameters.html#id43) that looks like this:

```json
[{"score":0.9906457662582397,"label":"person","box":{"xmin":17,"ymin":1248,"xmax":133,"ymax":1581}},{"score":0.9880649447441101,"label":"person","box":{"xmin":1267,"ymin":1280,"xmax":1310,"ymax":1394}},{"score":0.9975935816764832,"label":"car","box":{"xmin":210,"ymin":1302,"xmax":1365,"ymax":1725}},{"score":0.9364981055259705,"label":"person","box":{"xmin":632,"ymin":1261,"xmax":706,"ymax":1368}},{"score":0.9867833852767944,"label":"car","box":{"xmin":1437,"ymin":1305,"xmax":1621,"ymax":1367}},{"score":0.9914701581001282,"label":"person","box":{"xmin":379,"ymin":1277,"xmax":487,"ymax":1421}},{"score":0.9932585954666138,"label":"person","box":{"xmin":1383,"ymin":1256,"xmax":1470,"ymax":1408}},{"score":0.9995352029800415,"label":"car","box":{"xmin":825,"ymin":1320,"xmax":2536,"ymax":2037}}]
```

A very simple JS code example to call the API with a local image loaded:

```js
import fetch from "node-fetch";
import fs from "fs";

async function query(filename) {
  const data = fs.readFileSync(filename);
  const response = await fetch(
    "https://api-inference.huggingface.co/models/facebook/detr-resnet-50",
    {
      headers: {
        Authorization: `Bearer YOUR_API_TOKEN_HERE`,
      },
      method: "POST",
      body: data,
    }
  );
  const result = await response.json();
  return result;
}

query(
  "image.jpeg"
).then((response) => {
  console.log(JSON.stringify(response));
});
```

For a URL image, just send the URL in the body.

**Comment by bbenoist** [comment]
> The image size is 10Mb max, bigger will return a 413 status code

Have you tested whether we can send images bigger than 10MB when using a URL?

On some other services (e.g. Speechmatics) the same limits exists but only when the image data is in the body. They remove it when the image is passed as a URL.

**Comment by Jordanlelay** [comment]
> Have you tested whether we can send images bigger than 10MB when using a URL?

It does work ! (15mb)

**Comment by nicOwlas** [comment]
V7 JS code to call a model:
```
const url = 'https://darwin.v7labs.com/ai/models/4b827bc9-bb0a-42dd-83fb-1c9907bb2103/infer'
const base64 = '...'
const body = { image: { base64: base64 } }
const token = 'your-api-key'
const headers = { Authorization: `ApiKey ${token}` }

fetch(url, { method: 'POST', body, headers })
```

**Comment by bbenoist** [comment]
Thanks @nicOwlas !

Input is OK with what's planned.
And I've found in the documentation that the image property can be a URL too so we can avoid base64 and use an S3 signed URL instead.

For the output, it looks quite normal, _despite the fact that defining polygon points with a list of `{x, y}` objects instead of 2D arrays or binary data adds a lot of useless bytes_.  
But, as for Roboflow and HugginFace, we still need to determine the way we can process it without provider-specific code.

**Comment by nicOwlas** [comment]
Pricing Plans
- Each AiAssistant is available to one or more plans (eg: COCO AiAssistant to Starter, COCO and Distribution Grid to Pro etc.)
- Each plan come with a given amount of AiAssistant annotations
- Possibility to buy extra AiAssistant annotations packages to cover individual usages
