### ISSUE TITLE
Implement `runAiAssistant` GraphQL resolver and UI

### ISSUE THREAD

**Issue by bbenoist** [labelflow/labelflow#823]
## Description

As we shouldn't call directly external AI Assistants from the client but from our backend, we need to implement appropriate mutations.

## Technical considerations

They are multiple ways to run such processing from our backend:
* Assume that the query to the remote service won't last long (`our_own_processing_time + remote_query_time < vercel_lambda_timeout`) and implement a top-level **_synchronous_** `runAiAssistant` mutation.
* Assume that a query to the remote service _can_ last longer than Vercel lambdas timeouts and move the GraphQL server out of Vercel (so that we could have our own bigger timeout value).
* Assume that a query to the remote service _can_ last long (_don't forget Vercel lambdas timeouts_) and implement an _**asynchronous**_ job system:
  * `startJob` would add a job in a dedicated queue. Aditionally, we could add the `getJobs` and `getJob` queries and a `cancelJob` mutation.
  * Microservices would listen to the job queue and create the new labels if the remote request succeeded.
  * Then, they are multiple ways to propagate the new labels to the end-user:
    * 🚀 GraphQL subscriptions ([not supported with Lambdas/Vercel](https://vercel.com/support/articles/do-vercel-serverless-functions-support-websocket-connections)).
    * 😿 Poll regularly for new labels
    * ~~💩 Ask the end-user to refresh the page or refresh it automatically after a given time~~

## Technical solution

```gql
type RunAiAssistantInput {
  aiAssistantId: ID!
  imageId: ID!
}

type Mutation {
  runAiAssistant(where: RunAiAssistantInput): [Label!]
}
```

See #811 for details of the `AiAssistant*` models.

## Tasks

A solution assuming that remotes service calls can exceed our lambda timeout is more complex to implement.
In that sense, we'll go for the first way of doing things: **implement a top-level **_synchronous_** `runAiAssistant` mutation**

- [ ] Implement `runAiAssistant` mutation
- [ ] Non existing `LabelClasses` returned but the assistant are created
- [ ] Pin models to LabelFlow HugginFace account
  - [ ] For models which are long to start: make a check if the model is running. If it is not: display a notification to the user stating the we are starting the model and that he retry in 5 minutes
- [ ] Code AI Assistant menu component
  - [ ] One icon per model
  - [ ] One tool tip description per model
- [ ] Code specific post-processor for each AiAssistant to handle the different output formats
- [ ] Find proper shortcut for the `Annotate` button

## List of initially supported models
- [DETR - COCO](https://huggingface.co/facebook/detr-resnet-50) (object detection)
  - Tool tip description: "Automatic object detection across [80 classes](https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda)"
- [Vision Transformer](https://huggingface.co/google/vit-base-patch16-224) (image classification)
  - Tool tip description: "Automatic image classification across [1000 classes](https://image-net.org/challenges/LSVRC/2012/browse-synsets.php)"

## Not part of this issue
- No mapping of `LabelClass` at this stage
- No settings button next to the annotate button

## Mockup
- [link to menu](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4233%3A30147) <img width="709" alt="image" src="https://user-images.githubusercontent.com/16015322/155316592-bbbd50f7-369d-4676-845f-d1d2da3170f9.png">
- [Labeling interface](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4233%3A33085) <img width="1212" alt="image" src="https://user-images.githubusercontent.com/16015322/155316695-4389028b-c42a-4563-9f61-ff342527cc96.png">

**Comment by nicOwlas** [comment]
@bbenoist we need to be able to track usage of AiAssistants. One way can be to store the `AiAssistantId` in the `smartToolInput` column of the Label table no?

<img width="407" alt="image" src="https://user-images.githubusercontent.com/16015322/156362037-8e97e9c0-6645-4b66-b2ad-c0edda9f1c4d.png">

**Comment by nicOwlas** [comment]
Or add an `author` column (can be done in another issue). We just need to think to the best option.

**Comment by bbenoist** [comment]
Actually, it's more complicated than just using a dedicated field.

As-soon-as we'll have the asynchronous new backend and microservices implementation, AiAssistant tasks should be considered as any task.

We have then 2 options:
* Consider that the entities author is the person who triggered the task.
* Consider that the entities author is the task template (what we call an AiAssistant for now)
* Consider that the entities author is the task
