### ISSUE TITLE
Fix the sign-in not working on deployed branches

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#847]
## Context
The invitation email contains localhost:3000 in the invitation url instead of the vercel URL

## Tasks
- [ ] Investigate why an env var is not injected anymore
  - [ ] NextAuth defaults to localhost:3000 instead of the vercel URL
  - [ ] Breaking change when doing the JWT issue
- [ ] Test if invitation works before JWT & sitemap

## Useful links
- https://github.com/nextauthjs/next-auth/issues/497

**Comment by Jordanlelay** [comment]
Currently trying something, this setting was not ticked:

<img width="873" alt="Capture d’écran 2022-02-03 à 12 31 43" src="https://user-images.githubusercontent.com/43350109/152335743-cb15479e-f6a3-4e77-8d5c-6c9232259857.png">

**Comment by nicOwlas** [comment]
Fixed by Jordan
