### ISSUE TITLE
Update image card in image gallery

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#853]
## Tasks

- [x]  update image card in gallery (fill not fit)
- [x] Default state
  - [x] Put a black gradient covering the lower third of the image with 40% transparency
  - [x] Name is semi-bold fond
- [x] Hover state
  - [x] 40% transparency layer above the entire card
  - [x] Add the bin in the top right
- [x] on hover the bin button darkens

## Mockup
- [Link to Figma](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4907%3A19401)
<img width="827" alt="image" src="https://user-images.githubusercontent.com/16015322/157250905-d3354e57-3870-40df-becd-98597b100a02.png">

**Comment by geoffreyvancassel** [comment]
@nicOwlas can you please finish grooming this one and add the mock up?
