### ISSUE TITLE
Bulk delete of images

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#854]
## Tasks

- [x] Add a checkbox icon on the image card
- [x] When selected the card is in hover mode
- [x] Display the bulk action buttons at the top
- [x] Drop shadow below the bulk action buttons (2 pixels, blur 4, gray-200 as Figma)
- [x] Please respect button font colors, size and height of tool bar (let me know if you need to change things compared to the mockup)
- [x] `Select` button states
  - [x] If 0 images are selected the `Select` button displays `Select all`.
  - [x] If one or more images are selected the `Select` button displays `Deselect all`
  - [x] `Select all` selects the item displayed on the page only
  - [x] We store the list of image ids selected. We display the delete action on every pages if at least one item is in the list of selected items
  - [x] Clear the list of selected items when the user quits the gallery
- [x] Display confirmation modal when user presses delete (same as today but with the updated text).
  - [x] Delete the selected images together with their labels
- [x] Make the top nav bar always visible
- [x] Keep the navigation bar always visible
- [x] Display the number of selected items in the bottom right (cf mockup)

**Extra**
- [x] Reduce height of top navbar (where we have the breadcrumbs) from 72 to 56 pix (I don't know why and when it was increased to 72). Mockup shows 56. Reduce padding to `--chakra-space-2`

## Mockup

- [Bulk action buttons](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4989%3A20244)
<img width="605" alt="image" src="https://user-images.githubusercontent.com/16015322/158191152-2a9da0a6-9947-4e4b-a315-9954f73ce2cf.png">

- [Image gallery with bulk delete buttons](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4907%3A19401)
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/16015322/158193541-6d0f4f64-7a2f-42fd-9bde-79e9261bee60.png">

- [Confirmation modal Figma](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4607%3A17195)
<img width="786" alt="image" src="https://user-images.githubusercontent.com/16015322/157850897-e8fc2aa9-5714-47b8-b928-f09b74ca1898.png">

Depends on #853

**Comment by nicOwlas** [comment]
@Jordanlelay you are going to hate me, but can we keep the bin on each image card?:-/ (Baptist suggestion that I took time to agree with). It's better for the user who wish to delete only an image.
The hover on the bin is updated, filled with no transperancy, the current design was not good, we hardly see the hover.
