### ISSUE TITLE
Release the User Role to Starter and Pro Plans

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#878]
## Context

Roles are necessary to be able to distribute work to some people without compromising data integrity.
4 roles:
- Owner: Everything
- Admin: Everything but billing
- User:
  - Cannot invite people to the workspace
  - Cannot delete other's dataset
  - Cannot change workspace settings
- Worker:
  - Cannot invite
  - Cannot delete a dataset
  - Cannot delete an image
  - Cannot invite people
  - Cannot import
  - Cannot export
  - Cannot change workspace settings

## Tasks
Goal of this issue is to release the user role:

- [ ] Add authorship to datasets (link to a user not a membership)
  - [ ] Add `createdBy` field on `labels`, `labelClass`, `images`, `datasets`, `workspaces`
  - [ ] Check authorship at deletion of datasets or images (check the authorisation matrix)
  - [ ] If a member leaves a workspace, his datasets are not transferred. Only admins and owners can then delete the dataset/
- [ ] Gray out the `member` tab and block url to the `member` page
- [ ] Gray out the `settings` tab and block url to the `settings` page
- [ ] `User` role can be selected only if the workspace is `Starter` or `Pro`
- [ ] When a workspace is downgraded: `User` cannot be selected anymore (we do not change the role of existing users)
