### ISSUE TITLE
Message on /local to invite creating an online workspace

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#886]
## Objective

Invite users going on labelflow.ai/local/* to create an online workpsace

## Task

- [ ] Display the page on labelflow.ai/local/* if the user is signed in or not
- [ ] Add Call to action to create an online workspace (which triggers the sign-in first right?). Redirects to labelflow.ai/
- [ ] Add secondary call to action to go home (website if user is not signed in, list of workspaces if he is signed in). Redirects to labelflow.ai/

## Mockup
- [Link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=4547%3A16744)
<img width="845" alt="image" src="https://user-images.githubusercontent.com/16015322/154053735-e1b78396-85e5-439f-8027-ba3bfd30ffbf.png">

**Comment by bbenoist** [comment]
Closed by #890
