### ISSUE TITLE
Map classes

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#927]
## Tasks

- [ ] Store in a table the raw output classes of every AiAssistant
  - [ ] AiAssistantId
  - [ ] DatasetId
  - [ ] RawOutputClassName
  - [ ] LabelClassId
  - [ ] Toggle adds or remove a mapping in a table or do we store a boolean for every RawOutputClassName of the model?
  - [ ] Add a `createMany` and `deleteMany` or `updateMany` when activate all or disable all is toggled on/off.
