### ISSUE TITLE
Multiple selection of labels on the labeling view

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#937]
## Tasks
- [ ] `ctrl/cmd + a` to select all labels on an image
- [ ] `ctrl+cmd + left click` selects all the labels in the area
- [ ] selected labels can be deleted with the bin button or `d` / `backspace keys`
- [ ] selected labels can be assigned to a class selected in the class selector
- [ ] class selector displays `Mixed` when several labels of various LabelClass are selected
