### ISSUE TITLE
Add Trial countdown in navbar with call to action

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#956]
## Tasks

- [ ] Add a trial countdown in the navbar
  - [ ] Green when trial >= 6 days
  - [ ] Orange when trial >= 2 days
  - [ ]  Red when trial < 2 days
- [ ] Query the number of remaining trial days from Stripe
- [ ] Add a call to action to the stripe page for the user to upgrade his plan

**Comment by nicOwlas** [comment]
After some investigation, option 1 above seems to be the more straight forward.
- We create 2 new plans
  - `Starter trial`
  - `Pro trial`
- The newly created workspaces will be:
  - `Pro trial` by default when clicking in the upper right call to action.
  - `Starter trial` or `Community` when selected from the plan cards at the bottom of the website
- The 2 trial plans will not be available from Stripe customer portal (we can select which products are visible in the portal, [link here to configure](https://dashboard.stripe.com/test/settings/billing/portal)
- When clicking on Select plan in the navigation bar, the user will be able to select one of the 3 plans (Community, Starter, Pro) during his trial period

**Comment by nicOwlas** [comment]
The customer portal would look like this (I've put a fake price for Pro trial, should likely be set to $0):
![image](https://user-images.githubusercontent.com/16015322/160660403-76a694fc-59c0-427f-adab-199f781d4f08.png)

**Comment by nicOwlas** [comment]
Following todays discussion, we will not create new plans to start with. The call to action will direct to the Manage Billing page (same Stripe URL as the one in the Workspace Settings page)
