### ISSUE TITLE
Follow AI Assistant usage

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#958]
## Tasks
- [ ] Add a column to the Label table. `AiAssistantId` (optional)
- [ ] Every label created by an AI Assistant has the AI Assistant Id filled in

**Not part of this issue**
- [ ] Display the number of labels created by an AI Assistant and Auto-Polygon in the workspace
- [ ] Count number of images inferred (the ones that have one or more labels with an `id` in the `AiAssistantId` )

**Comment by nicOwlas** [comment]
Was done in #823
