### ISSUE TITLE
Fix bug on tutorial images

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#966]
## Tasks
To reproduce:
- [ ] Create a new workspace
- [ ] Check the tutorial images: all good
- [ ] Log out and log back in
- [ ] Open the labeling view on the tutorial dataset
- [ ] Thumbnails are fine but original images are not found
