### ISSUE TITLE
Fix width of end of trial banner

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#974]
## Observation
- Banner is not large enough, there is a return to line though there is still lots of space to the right and left.
- Banner is only visible on the dataset page, it should be visible on **every** pages of the workspace (gallery, labeling view, members, settings etc. etc.)
- Call to action should lead to the Stripe Manage Billing page (the one that is linked in the settings page), that was not explicitly written in the issue. Mea Culpa.

## Tasks

- [ ] Make the max width of the banner larger so that in full size window on a laptop there is no return to line
- [ ] Add the banner on every pages of the workspace
- [ ] Change the redirection of the call to action `Upgrade Plan` for the Stripe Manage Billing page

![image](https://user-images.githubusercontent.com/16015322/161006801-5ca377d7-ada1-4f22-8436-55178bdea765.png)
