### ISSUE TITLE
Add "Project" > "Project Name" to breadcrumbs

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like (import visuals when possible)**

- [x] Update breadcrumbs when on a project: "Projects" > "Project Name" (#95)
- [x] Update url to include `projects/projectId/images/imageId`
- [ ] ~~When one click on "Project Name" or "Images" in the breadcrumbs the last visited image is displayed~~ moved to #112 
- [x] When one click on "Projects" in the breadcrumbs the list of projects is displayed (#95)
- [ ] ~~When one comes back on a project, the first image is displayed or empty state of project is displayed~~ Moved to #274

**Describe alternatives you've considered**

**Additional context**
blocked by #95
